//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsccWebTeam.ServiceClosures.AdministrationTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Czone.WebService.SchoolsInformation/SchoolsInformationWebServic" +
            "e.asmx")]
        public string EsccWebTeam_ServiceClosures_AdministrationTool_SchoolsInformationService_SchoolsInformationWebService {
            get {
                return ((string)(this["EsccWebTeam_ServiceClosures_AdministrationTool_SchoolsInformationService_SchoolsI" +
                    "nformationWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sqBBKghFjYNv84oy4ouLdA")]
        public string SchoolTwitterConsumerKey {
            get {
                return ((string)(this["SchoolTwitterConsumerKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TCW3WtfspIhfSIQtR4fKDQUZ1Lmx5jdFkcSVEoqpCLI")]
        public string SchoolTwitterConsumerSecret {
            get {
                return ((string)(this["SchoolTwitterConsumerSecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("174187586-mNSz7ktgLpFQdRZEjEce4w26o9Di3M8R9arIyXfw")]
        public string SchoolTwitterAccessToken {
            get {
                return ((string)(this["SchoolTwitterAccessToken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dPYp26zBOiid4Y3ORK5wUOVv6ORfscWpUDGKAvI1XwM")]
        public string SchoolTwitterAccessTokenSecret {
            get {
                return ((string)(this["SchoolTwitterAccessTokenSecret"]));
            }
        }
    }
}
